//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilitiesManager
    {
        public int FacitlitiesManagerId { get; set; }
        public string OtherSystemRef { get; set; }
        public string Telephone { get; set; }
        public string FMCode { get; set; }
    }
}
